export const projects = [
	{
		id: 0,
		title: 'BookSyNation',
		image: 'Bookcine',
		frame: 'Bookcine2',
		subtitle: 'Software Development 1 Project',
		desc: 'BookSyNation is a mobile simulation game that will help in developing awareness for waste reduction and pollution. With its inherent game mechanics, the users shall be able to engage and gain more knowledge about waste management as they play.',
		viewButton: 'two',
	},
	{
		id: 1,
		title: 'ReCycl3R',
		image: 'Recycler',
		frame: 'Recycler2',
		subtitle: 'Accenture Program the Future 2021',
		desc: 'Recycl3R is a mobile simulation game that will help in developing awareness for waste reduction and pollution. With its inherent game mechanics, the users shall be able to engage and gain more knowledge about waste management as they play.',
		viewButton: 'two',
	},
	{
		id: 2,
		title: 'WhiteList',
		image: 'Whitelist',
		frame: 'Whitelist2',
		subtitle: 'Modern Systems and Design Project',
		desc: 'WhiteList is a centralized informational display hub of various rentable locations within Cebu. It was developed using React, HTML, and CSS along with Firebase as its authentication and database.',
		viewButton: 'two',
	},
	{
		id: 3,
		title: 'DataGrades',
		image: 'Datagrades',
		frame: 'Datagrades2',
		subtitle: 'Software Design Project',
		desc: 'DataGrades is a mobile simulation game that will help in developing awareness for waste reduction and pollution. With its inherent game mechanics, the users shall be able to engage and gain more knowledge about waste management as they play.',
		viewButton: 'two',
	},
	{
		id: 4,
		title: 'AltruWiz',
		image: 'Altruwiz',
		frame: 'Altruwiz2',
		subtitle: 'Software Development',
		desc: 'AltruWiz is a mobile simulation game that will help in developing awareness for waste reduction and pollution. With its inherent game mechanics, the users shall be able to engage and gain more knowledge about waste management as they play.',
		viewButton: 'two',
	},
];
